language: python
python: "3.7"

env:
  - SCRIPT=travis/python-linter.sh
    INSTALL=travis/python-setup.sh
    SEND_ON_FAIL=FALSE

  - SCRIPT=travis/python-unitest.sh
    INSTALL=travis/python-setup.sh
    SEND_ON_FAIL=FALSE

  - SCRIPT=travis/react-unittest.sh
    INSTALL=travis/react-setup.sh
    SEND_ON_FAIL=FALSE

  - SCRIPT=travis/react-linter.sh
    INSTALL=travis/react-setup.sh
    SEND_ON_FAIL=FALSE

  - SCRIPT=travis/e2e.sh
    INSTALL=travis/e2e-setup.sh
    SEND_ON_FAIL=TRUE

services:
  - mysql

before_script:
  - bash $INSTALL

script:
  - bash $SCRIPT

after_failure:
  - once
  - python manage.py send_failed_videos
