language: python
python: "3.7"

env:
  - SCRIPT=travis/python-linter.sh
    INSTALL=travis/python-setup.sh

  - SCRIPT=travis/python-unitest.sh
    INSTALL=travis/python-setup.sh

  - SCRIPT=travis/react-unittest.sh
    INSTALL=travis/react-setup.sh

  - SCRIPT=travis/react-linter.sh
    INSTALL=travis/react-setup.sh

  - SCRIPT=travis/e2e.sh
    INSTALL=travis/e2e-setup.sh
    SEND_ON_FAIL=1

services:
  - mysql

before_script:
  - bash $INSTALL
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

script:
  - bash $SCRIPT

after_failure:
  - python manage.py send_failed_videos
