language: python
python: "3.7"

env:
  - SCRIPT=travis/linter.sh
    INSTALL=travis/python_setup.sh

  - SCRIPT=travis/unitest.sh
    INSTALL=travis/python_setup.sh 1

services:
  - mysql

install:
  - bash $INSTALL

script:
  - bash $SCRIPT
