language: python
python: "3.7"

before_install:
  - pip install pycodestyle

env:
  - SCRIPT=travis/linter.sh
    INSTALL=travis/python_setup.sh

  - SCRIPT=travis/unitest.sh
    INSTALL=travis/python_setup.sh 1

install:
  - echo $BEFORE

services:
  - mysql

script:
  - bash $SCRIPT
