language: python
python: "3.7"

before_install:
  - pip install pycodestyle

env:
  - SCRIPT=travis/linter.sh, BEFORE=pip_install.sh
  - SCRIPT=travis/unitest.sh, BEFORE=pip_install.sh

install:
  - pip install -r requirements.txt
  - mysql -e 'CREATE DATABASE bifrost;'
  - cp bifrost/local_settings.travis.py bifrost/local_settings.py

services:
  - mysql

script:
  - echo $BEFORE
  - bash $SCRIPT
