language: python
python: "3.6"

before_install:
  - pip install pycodestyle

install:
  - pip install -r requirements.txt
  - mysql -e 'CREATE DATABASE bifrost;'
  - cp bifrost/local_settings.travis.py bifrost/local_settings.py

services:
  - mysql

script:
  - pycodestyle  . --exclude=settings.py,migrations
  - python manage.py migrate
  - python manage.py test