language: python
python: "3.7"

env:
  - SCRIPT=travis/python-linter.sh
    INSTALL=travis/python-setup.sh

  - SCRIPT=travis/python-unitest.sh
    INSTALL=travis/python-setup.sh

  - SCRIPT=travis/react-unittest.sh
  - INSTALL=travis/react-setup.sh

services:
  - mysql

before_script:
  - bash $INSTALL

script:
  - bash $SCRIPT
