language: python
python: "3.6"

before_install:
  - pip install pycodestyle

env:
  - SCRIPT=travis/linter.sh
  - SCRIPT=travis/unitest.sh

install:
  - pip install -r requirements.txt
  - mysql -e 'CREATE DATABASE bifrost;'
  - cp bifrost/local_settings.travis.py bifrost/local_settings.py

services:
  - mysql

script:
  - bash $SCRIPT
