# Generated by Django 2.2.6 on 2019-11-15 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bifrost_timeline', '0001_initial'),
        ('bifrost_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('agency', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bifrost_location.Location')),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingConjunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bifrost_location.Location')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('extra_info', models.TextField()),
                ('connection_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_events.Flight')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bifrost_location.Location')),
                ('timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bifrost_location.Location')),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
