# Generated by Django 2.2.6 on 2019-11-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bifrost_timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('extra_info', models.TextField()),
                ('connection_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_events.Flight')),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
