# Generated by Django 2.2.6 on 2019-11-07 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bifrost_timeline', '0001_initial'),
        ('bifrost_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('agency', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingConjunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('members', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
