# Generated by Django 3.0.3 on 2020-03-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost_location', '0001_initial'),
        ('bifrost_timeline', '0001_initial'),
        ('bifrost_events', '0003_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bifrost_location.Location')),
                ('timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bifrost_timeline.Timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
