# Generated by Django 2.2.6 on 2019-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('lat', 'long')},
            },
        ),
    ]
