# Generated by Django 2.2.6 on 2019-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost_location', '0002_auto_20191109_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
