# Generated by Django 2.2.6 on 2019-11-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost_location', '0003_auto_20191109_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
