# Generated by Django 2.2.6 on 2019-11-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bifrost_location', '0004_auto_20191109_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'long')},
        ),
    ]
